version: '3'

services:
  php:
    build:
      context: ./symfony
    container_name: php
#    depends_on:
#      - postgres
    env_file:
      - ./symfony/.env
    volumes:
      - ./symfony:/srv/symfony:rw,cached
    environment:
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost idekey=IDE_XDEBUG"
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
#    links:
#        - blackfire:blackfire
    networks:
      - network

  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile.nginx
    container_name: symfony
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./symfony/public:/srv/symfony/public:ro
    networks:
      - network

#  postgres:
#    # In production, you may want to use a managed database service
#    image: postgres:9.6-alpine
#    container_name: postgres
#    environment:
#      - POSTGRES_DB=symfony
#      - POSTGRES_USER=symfony
#      - POSTGRES_PASSWORD=symfony
#      - PGDATA=/var/lib/postgresql/data/db-files/
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#    # - ./docker/db/data:/var/lib/postgresql/data:rw
#    ports:
#      - "5432:5432"
#    networks:
#      - network

  blackfire:
    image: blackfire/blackfire
    container_name: blackfire
    depends_on:
      - php
    environment:
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
      BLACKFIRE_LOG_LEVEL: 4
    ports:
      - "8707:8707"
    networks:
      - network

  h2-proxy:
    # Don't use this proxy in prod
    build:
      context: ./h2-proxy
      dockerfile: ./Dockerfile
    container_name: h2-proxy
    depends_on:
      - symfony
    ports:
      - "80:80"
      - "443:443"
#    environment:
#      NGINX_ENABLED_VHOST: blackfire.localhost
#    extra_hosts:
#          - "blackfire.localhost:127.0.0.1"
    networks:
      - network

#volumes:
#  db-data: {}

networks:
  network:
    driver: bridge